### ISSUE TITLE
artisan vendor:publish does not copy View files and SVGS to Public directory.  

### ISSUE THREAD

**Issue by mohitpawar10** [LaravelCollective/errors#3]
Laravel does detect new package after installing but when trying to publish files it does not detect new package.

Below are steps to replicate the issue. 
1) Install laravel Package using composer.
2) Try Vendor publish command it will not show laravelcollective/errors providers.   

Machine Details
1) OS - Windows 10
2) PHP Version - 7.1.16
3) Laravel - 5.8.35
4) Composer  - 1.5.2

I suspect an issue with ServiceProvider. I added Service Provider manually in config/app.php still I wasn't able to see laravelcollective/errors provider. 

See below screenshot from git bash. 
 
![Screenshot (87)](https://user-images.githubusercontent.com/14096291/65376198-cd6cd400-dcba-11e9-9d90-4f672870a730.png)

**Comment by mlantz** [comment]
Should be resolved with v1.0.1
